let base = {
    trackItem: [
        'Утро которым мы умрём',
        'Love Will Tear Apart',
        'August',
        'Use Me',
        'Первый снег',
        'Моя',
        'Гагарин я вас любила',
        'Крайности',
        'Sleepwalker',
        'Твоего балкона свет!',
        'Abstract nonsense',
        'За углом',
        'Никотиновая доза',
        'Мутные пятна',
        'Pieces',
        'Buzzcocks',
        'I Dont Care Anymore',
        'Я знаю твой телефон',
        'Плачущий Блаженный',
        'Взгляд с экрана',
    ],
    trackArtst: [
        'Mujuice',
        'Alicia Widar',
        'Intelligency',
        'Alec Benjamin',
        'Сова',
        'kameraxstyle',
        'Ундервуд',
        'Кладбище Черновиков',
        'Illenium',
        'Пупок Комсомола',
        'Kagamine Rin',
        'Пустецкий',
        'СуШ(07)',
        'nutakoe',
        'Sum 41',
        'Ever Fallen In Love',
        'Cathedral Bells',
        'akaky',
        'miltei',
        'Наутилус Помпилиус',
    ],
        image: [
        '',
        'https://sujer-ux.github.io/pb.su/image/03.jpg',
        '',
        '',
        '',
        'https://sujer-ux.github.io/pb.su/image/04.jpg',
        '',
        'https://sujer-ux.github.io/pb.su/image/05.jpg',
        '',
        'https://sujer-ux.github.io/pb.su/image/06.jpg',
        '',
        'https://sujer-ux.github.io/pb.su/image/sujer-ux.jpg',
        'https://sujer-ux.github.io/pb.su/image/sush07.jpg',
        'https://sujer-ux.github.io/pb.su/image/nutakoe_pyatna.jpg',
        '',
        '',
        '',
        '',
        '',
        '',
    ],
    song: [
        'media/songs/Утро которым мы умрём   Mujuice.mp3',
        'media/songs/widar_love.mp3',
        'media/songs/August   Intelligency.mp3',
        'media/songs/Nightcore - Use me (Lyrics) (320 kbps).mp3',
        'media/songs/Первый снег   Сова.mp3',
        'media/songs/kameraxstyle_moya.mp3',
        'media/songs/Гагарин_я_вас_любила_Избранное_Ундервуд.m4a',
        'media/songs/kch_krainosti.mp3',
        'media/songs/Sleepwalker   Illenium.mp3',
        'media/songs/komsomola_svet.mp3',
        'media/songs/Abstract nonsense   Kagamine Rin.mp3',
        'media/songs/pustetskiy_uglom.mp3',
        'media/songs/sush_doza.mp3',
        'media/songs/nutakoe_pyatna.mp3',
        'media/songs/Pieces   Sum 41.mp3',
        'media/songs/Buzzcocks-Ever_Fallen_In_Love.mp3',
        'media/songs/Cathedral Bells - I Dont Care Anymo... - V3H.mp3',
        'media/songs/Я знаю твой телефон - akaky.m4a',
        'media/songs/плачущий_блаженный_cover_сияние_72_катя_милтей.mp3',
        'media/songs/Взгляд_с_экрана_Наутилус_Помпилиус.mp3',
    ],
};
